services:
  shortsmate-help:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    expose:
      - "80"
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
